Add demo for lab4
cs-pub-ro/SOC pull request #6
Opened 2024-03-20 19:40 UTC by MathewColin

2024-03-20 19:50 UTC, dosarudaniel approved these changes
Looks good to me

2024-03-21 07:29 UTC, teodutu requested changes
The demo's OK but its coding style differs from our usual one.

2024-03-21 07:29 UTC, teodutu commented on lab04/lab4.srcs/sources_1/new/basicFSM.v
> +    // Tranzi?ie condi?ionat?: bloc always@ ( * )
```suggestion
    // Tranziție condiționată: bloc always@ ( * ) 
```

2024-03-21 07:29 UTC, teodutu commented on lab04/lab4.srcs/sources_1/new/basicFSM.v
> +            //Daca automatul ajunge  n aceste stari se va reseta.
```suggestion

            // Stări pentru tratarea erorilor
            // Dacă automatul ajunge în aceste stări se va reseta.
```

2024-03-21 07:29 UTC, teodutu commented on lab04/lab4.srcs/sources_1/new/basicFSM.v
We use a different reg/wire naming convention for most labs. Use the same convention here as in the test module for example.

2024-03-21 08:27 UTC, mariateonaolteanu23 commented on lab04/lab4.srcs/sources_1/new/basicFSM.v
We used the same naming convention/code as in the OCW example - it's easier to follow. Do you still feel we should change the naming convention?

2024-03-21 08:30 UTC, teodutu commented on lab04/lab4.srcs/sources_1/new/basicFSM.v
Yes, it's important to be consistent. The students have already seen the existing convention and are starting to get used to it. Better update code on the OCW.

2024-03-21 09:44 UTC, teodutu approved these changes
Seems legit.

2024-03-21 09:45 UTC, teodutu commented
Better squash the commits into a single one before merging this to have a more unitary history.

2024-03-21 17:57 UTC, merged